# -*- coding: utf-8 -*-
"""Copy_of_Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/adarsh25scs1003005017-cell/Adarsh_25SCS1003005017_IILM_GN/blob/main/Copy_of_Untitled2.ipynb
"""

# ================================
# AI + Tourism Project (India)
# Foreign Tourist Arrivals 2019–2023
# ================================

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# 1️⃣ CREATE DATASET (Realistic tourism data for India)
data = {
    "Year": [2019, 2020, 2021, 2022, 2023],
    # Foreign Tourist Arrivals (in Millions)
    "Foreign_Tourist_Arrivals_Million": [10.93, 2.74, 1.52, 6.19, 9.20]
}

df = pd.DataFrame(data)
print("=== Tourism Data (India: Foreign Tourist Arrivals 2019–2023) ===")
print(df)

# (Optional) Save dataset as CSV file for your project file
csv_file_name = "india_tourism_fta_2019_2023.csv"
df.to_csv(csv_file_name, index=False)
print(f"\nDataset saved as: {csv_file_name}")

# 2️⃣ BASIC INFO & SUMMARY
print("\n=== Data Info ===")
print(df.info())

print("\n=== Summary Statistics ===")
print(df.describe())

# 3️⃣ ADD YEAR-ON-YEAR GROWTH (%)
df = df.sort_values("Year")  # just to be safe

df["YoY_Growth_%"] = df["Foreign_Tourist_Arrivals_Million"].pct_change() * 100
print("\n=== Data with Year-on-Year Growth (%) ===")
print(df)

# 4️⃣ GRAPH 1 – LINE CHART OF TOURIST ARRIVALS
plt.figure(figsize=(8, 5))
plt.plot(df["Year"], df["Foreign_Tourist_Arrivals_Million"], marker="o")
plt.title("Foreign Tourist Arrivals in India (2019–2023)")
plt.xlabel("Year")
plt.ylabel("Arrivals (Million)")
plt.grid(True)
plt.tight_layout()
plt.show()

# 5️⃣ GRAPH 2 – BAR CHART OF YoY GROWTH
plt.figure(figsize=(8, 5))
plt.bar(df["Year"], df["YoY_Growth_%"])
plt.title("Year-on-Year Growth in Foreign Tourist Arrivals (2019–2023)")
plt.xlabel("Year")
plt.ylabel("Growth (%)")
plt.axhline(0, linestyle="--")
plt.tight_layout()
plt.show()

# 6️⃣ SIMPLE AI / ML PART – LINEAR REGRESSION TO PREDICT 2024

# Feature (X) and Target (y)
X = df[["Year"]]  # 2D
y = df["Foreign_Tourist_Arrivals_Million"]

# Create and train the model
model = LinearRegression()
model.fit(X, y)

# Predict for 2024
year_to_predict = np.array([[2024]])
pred_2024 = model.predict(year_to_predict)[0]

print(f"\n=== AI Prediction ===")
print(f"Predicted Foreign Tourist Arrivals in India for 2024: {pred_2024:.2f} million")

# 7️⃣ PLOT ACTUAL vs PREDICTED
years_extended = list(df["Year"]) + [2024]
arrivals_extended = list(df["Foreign_Tourist_Arrivals_Million"]) + [pred_2024]

plt.figure(figsize=(8, 5))
plt.plot(df["Year"], df["Foreign_Tourist_Arrivals_Million"], marker="o", label="Actual (2019–2023)")
plt.plot(2024, pred_2024, marker="x", markersize=10, label="Predicted 2024")
plt.title("Actual and Predicted Foreign Tourist Arrivals in India")
plt.xlabel("Year")
plt.ylabel("Arrivals (Million)")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()